# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 2.6.3"

gem "rails", "~> 6.0.0"
gem "rails-i18n"

# Use postgresql as the database for Active Record
gem "pg", ">= 0.18", "< 2.0"

# Use Puma as the app server
gem "puma", "~> 4.3"
# Use development version of Webpacker
gem "webpacker", "~> 4.0"
gem "slim-rails"

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem "turbolinks", "~> 5"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.5"
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false

gem "pry-rails"

gem "config"

gem "devise"
gem "devise_invitable"
gem "devise-i18n"

gem "meta-tags"

gem "browser"

gem "kaminari"
gem "form_core"
gem "timeliness-i18n"
gem "validates_timeliness", "~> 5.0.0.alpha4"
gem "acts_as_list"
gem "cocoon"
gem "script_core"
gem "activeentity", "~> 0.0.1.beta13"
gem "workflow_core", "~> 0.0.2"
gem "globalid"

gem "faraday"
gem "faraday_middleware"

gem "faker"
gem "graphviz"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "pry-byebug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem "web-console"
  gem "listen", ">= 3.0.5", "< 3.2"

  gem "brakeman", require: false
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-performance", require: false

  # Use Capistrano for deployment
  gem "capistrano", "~> 3.11", require: false
  gem "capistrano-bundler", require: false
  gem "capistrano-rails", require: false
  gem "capistrano-rvm", require: false
  gem "capistrano3-puma", require: false
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem "capybara", ">= 2.15"
  gem "selenium-webdriver"
  gem "webdrivers"
end

group :circle_ci do
  gem "minitest-ci"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
